FROM python:3.5-alpine
RUN ["mkdir","/app"]
WORKDIR /app
COPY requirements.txt .
RUN ["pip","install","--no-cache-dir","-r","requirements.txt"]
ADD . .
VOLUME ["/data.txt"]
EXPOSE 8000
ENV PYTHONPATH /app/src
ENTRYPOINT ["python","-m","server"]
